CREATE DATABASE todo_db;

\c todo_db;

CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    status VARCHAR(255),
    observacoes VARCHAR(255),
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),

    CONSTRAINT tarefas_status_check
        CHECK (status IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA'))
);